"""create user and profile tables

Revision ID: e07644577837
Revises:
Create Date: 2026-10-06 23:34:08.419084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e07644577837"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """创建账户、两种角色资料及候选人技能表。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum(
                "candidate",
                "employer",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "candidate_profile",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resume_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "employer_profile",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "company_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "candidate_skill",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint(
            "length(name) > 0 AND name = lower(trim(name))",
            name="ck_candidate_skill_normalized_name",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate_profile.user_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id", "name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """按外键依赖的逆序删除本次创建的表。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidate_skill")
    op.drop_table("employer_profile")
    op.drop_table("candidate_profile")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
